name: Bug
description: Report a bug or an issue.
title: '[Bug] '
labels: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the issue is.
    validations:
      required: true
  - type: textarea
    id: crashlog
    attributes:
      label: Crashlog
      description: If your game crashes, please attach the crash log or latest.log here
    validations:
      required: true
  - type: textarea
    id: reproducing
    attributes:
      label: Steps to reproduce
      description: How do you trigger this bug?
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: dropdown
    id: operating-systems
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: false
  - type: input
    id: adddon-version
    attributes:
      label: Addon Version
      description: You can put commit hash of the version of the addon you are using.
    validations:
      required: false
  - type: input
    id: meteor-version
    attributes:
      label: Meteor Version
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
    validations:
      required: true
  - type: textarea
    id: mods
    attributes:
      label: Other mods
      description: What other mods you may be using?
      value: |
        1.
        2.
        3.
        ...
      render: plaintext
    validations:
      required: false